version: '2'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: word.cy5rftlokiyu.us-east-1.rds.amazonaws.com:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: proyecto2
      WORDPRESS_DB_NAME: word
